ubuntu-latest:
    image: ubuntu:latest
    script:
        - sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        - DEBIAN_FRONTEND=noninteractive apt-get -qq update
        - DEBIAN_FRONTEND=noninteractive apt-get -yqq build-dep mlt
        - DEBIAN_FRONTEND=noninteractive apt-get -yqq install cmake
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

ubuntu-lts:
    image: ubuntu:20.04
    script:
        - sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        - DEBIAN_FRONTEND=noninteractive apt-get -qq update
        - DEBIAN_FRONTEND=noninteractive apt-get -yqq build-dep mlt
        - DEBIAN_FRONTEND=noninteractive apt-get -yqq install cmake
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

debian-unstable:
    image: debian:unstable
    script:
        - echo 'deb-src http://deb.debian.org/debian unstable main' >> /etc/apt/sources.list
        - apt-get -qq update
        - apt-get -yqq build-dep mlt
        - apt-get -yqq install cmake
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

debian-testing:
    image: debian:testing
    script:
        - echo 'deb-src http://deb.debian.org/debian testing main' >> /etc/apt/sources.list
        - apt-get -qq update
        - apt-get -yqq build-dep mlt
        - apt-get -yqq install cmake
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

debian-stable:
    image: debian:stable
    script:
        - echo -e 'deb-src http://deb.debian.org/debian stable main\ndeb-src http://deb.debian.org/debian stable-updates main' >> /etc/apt/sources.list
        - echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list
        - apt-get -qq update
        - apt-get -yqq build-dep mlt
        - apt-get -yqq install cmake
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

fedora-38:
    image: fedora:38
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++ cmake
            # unclear why `gcc-c++` isn't in `Development Tools`
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

fedora-36:
    image: fedora:36
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++ cmake
            # unclear why `gcc-c++` isn't in `Development Tools`
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

fedora-34:
    image: fedora:34
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++ cmake
            # unclear why `gcc-c++` isn't in `Development Tools`
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install

fedora-30:
    image: fedora:32
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++ cmake
            # unclear why `gcc-c++` isn't in `Development Tools`
        - cmake -DCMAKE_BUILD_TYPE=Debug . && make -j -f Makefile install
