ubuntu-daily:
    image: ubuntu:disco
    script:
        - sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        - DEBIAN_FRONTEND=noninteractive apt-get -qq update
        - apt-get -yqq build-dep mlt
        - ./configure --enable-gpl --enable-gpl3 && make && make install
            # there's no `check` or `test` `make` target

ubuntu-latest:
    image: ubuntu:cosmic
    script:
        - sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        - DEBIAN_FRONTEND=noninteractive apt-get -qq update
        - apt-get -yqq build-dep mlt
        - ./configure --enable-gpl --enable-gpl3 && make && make install
            # there's no `check` or `test` `make` target

ubuntu-lts-3:
    image: ubuntu:bionic
    script:
        - sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        - DEBIAN_FRONTEND=noninteractive apt-get -qq update
        - apt-get -yqq build-dep mlt
        - ./configure --enable-gpl --enable-gpl3 && make && make install
            # there's no `check` or `test` `make` target

ubuntu-lts-2:
    image: ubuntu:xenial
    script:
        - sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        - apt-get -qq update
        - apt-get -yqq build-dep mlt
        - ./configure --enable-gpl --enable-gpl3 && make && make install
            # there's no `check` or `test` `make` target

ubuntu-lts-1:
    image: ubuntu:trusty
    script:
        - sed -i '/^#\sdeb-src /s/^#//' "/etc/apt/sources.list"
        - apt-get -qq update
        - apt-get -yqq build-dep mlt
        - export CFLAGS="-std=gnu11"
        - ./configure --enable-gpl --enable-gpl3 && make && make install
            # there's no `check` or `test` `make` target

debian-testing:
    image: debian:buster
    script:
        - echo -e 'deb-src http://deb.debian.org/debian buster main\ndeb-src http://deb.debian.org/debian buster-updates main\ndeb-src http://security.debian.org buster/updates main' >> /etc/apt/sources.list
        - apt-get -qq update
        - apt-get -yqq build-dep mlt
        - ./configure --enable-gpl --enable-gpl3 && make && make install
            # there's no `check` or `test` `make` target

debian-stable:
    image: debian:stretch
    script:
        - echo -e 'deb-src http://deb.debian.org/debian stretch main\ndeb-src http://deb.debian.org/debian stretch-updates main\ndeb-src http://security.debian.org stretch/updates main' >> /etc/apt/sources.list
        - apt-get -qq update
        - apt-get -yqq build-dep mlt
        - ./configure --enable-gpl --enable-gpl3 && make && make install
            # there's no `check` or `test` `make` target

centos-7:
    image: centos:7
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel
        - export CFLAGS="-std=gnu11"
        - ./configure --enable-gpl --enable-gpl3 && make && make install

fedora-29:
    image: fedora:29
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++
            # unclear why `gcc-c++` isn't in `Development Tools`
        - ./configure --enable-gpl --enable-gpl3 && make && make install

fedora-28:
    image: fedora:28
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++
            # unclear why `gcc-c++` isn't in `Development Tools`
        - ./configure --enable-gpl --enable-gpl3 && make && make install

fedora-27:
    image: fedora:27
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++
            # unclear why `gcc-c++` isn't in `Development Tools`
        - ./configure --enable-gpl --enable-gpl3 && make && make install

fedora-26:
    image: fedora:26
    script:
        - yum --assumeyes groupinstall "Development Tools"
        - yum --assumeyes install yasm gavl-devel libsamplerate-devel libxml2-devel ladspa-devel jack-audio-connection-kit-devel sox-devel SDL-devel gtk2-devel qt-devel libexif-devel libtheora-devel libvorbis-devel libvdpau-devel libsoup-devel liboil-devel python-devel alsa-lib pulseaudio-libs-devel gcc-c++
            # unclear why `gcc-c++` isn't in `Development Tools`
        - ./configure --enable-gpl --enable-gpl3 && make && make install
