matrix:
  include:
    - language: c
      services:
        - docker
      before_install:
        - docker pull ubuntu:16.04
      script:
        - docker run -v $PWD:/root -w /root ubuntu:16.04 /bin/sh -c "sed -i -e 's/# deb-src/deb-src/' /etc/apt/sources.list && apt-get -qq update && apt-get -y build-dep melt && ./configure --enable-gpl --enable-gpl3 --enable-lumas && make -j"
    - language: python
      python: 3.7
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
      before_install: pip install flake8
      script:
        # stop the build if there are Python syntax errors or undefined names
        - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
